### ISSUE TITLE
[FEATURE REQUEST] Non-ISO date formatting 

### ISSUE THREAD

**Issue by saviorand** [mojoto/morrow.mojo#7]
My use case is to get the current timestamp in a specified format, specifically "%a, %d %b %Y %H:%M:%S %Z". 

I need this to submit my project, [Lightbug](https://github.com/saviorand/lightbug_http) to the TechEmpower benchmark (they require a specific format for Date HTTP response headers). 

I couldn't figure out how to this with Morrow. Perhaps there could be a `format()` function, [like in Arrow](https://github.com/arrow-py/arrow/blob/87a1a774aad0505d9da18ad1d16f6e571f262503/arrow/arrow.py#L1091)?

Thanks for the hard work, love this project!

**Comment by Prodesire** [comment]
Great request. We will study how to support it.

**Comment by shalei6698** [comment]
0.3.0 released, now can use `m.format("dddd, DD MMM YYYY HH:mm:ss ZZZ")` to get the current timestamp with "%a, %d %b %Y %H:%M:%S %Z" format
